# Generated by Django 4.0.3 on 2022-03-28 17:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gallery', '0002_image_date_posted'),
    ]

    operations = [
        migrations.RenameField(
            model_name='location',
            old_name='name',
            new_name='city',
        ),
        migrations.AddField(
            model_name='location',
            name='country',
            field=models.CharField(default='default country', max_length=50),
            preserve_default=False,
        ),
    ]
